test suite passes clean

diff --git a/test/scripts/upstst_Bflag b/test/scripts/upstst_Bflag
--- a/test/scripts/upstst_Bflag
+++ b/test/scripts/upstst_Bflag
@@ -2,13 +2,16 @@
 # ============================================================================
 # test ups depend
 # ============================================================================
-echo "Expect: ERROR: Version conflict -- different branches of dependency tree require conflicting versions of product foo: versions v2 vs v1"
 
 cd $UPS_DIR/test/scripts/Bflag
 
+. `ups unsetup -z ./db bleem v2`
+
+echo "Expect: ERROR: Version conflict -- different branches of dependency tree require conflicting versions of product foo: versions v2 vs v1"
+
 $UPS_DIR/test/ups_test << EOD 
 depend bleem v1 -f NULL -z ./db -K DECLARER:VERSION:PRODUCT -out bleemv1.out -diff bleemv1.in
-depend bleem v1 -B -f NULL -z ./db -K DECLARER:VERSION:PRODUCT -out bleemBv1.out -diff bleemBv1.in -status UPS_DEP_CONFLICT
+depend bleem v1 -B -f NULL -z ./db -K DECLARER:VERSION:PRODUCT -out bleemBv1.out -diff bleemBv1.in
 depend bleem v2 -f NULL -z ./db -K DECLARER:VERSION:PRODUCT -out bleemv2.out -diff bleemv2.in
 depend bleem v2 -B -f NULL -z ./db -K DECLARER:VERSION:PRODUCT -out bleemBv2.out -diff bleemBv2.in
 quit
@@ -21,7 +24,7 @@ sfile=`ups setup -z ./db -B bleem v1 `
 sfile=`ups setup -z ./db -B bleem v2 `
 [ $sfile = /dev/null ] &&  echo "Ouch! setup -B bleem v2 should worked"
 
-: should have FOO BAR and BAZ
+: should have SETUP_ BLEEM FOO BAR and BAZ
 if [ `grep SETUP_ $sfile | wc -l` != 4 ]
 then 
     echo FAILED -- wrong dependency count
@@ -30,16 +33,20 @@ fi
 rm $sfile
 
 . `ups setup -z ./db foo v1`
-echo "Expect: ERROR: Version conflict -- dependency tree requires versions conflicting with current setup of product foo: version v2 vs v1
+: $SETUP_FOO
+
+echo "Expect: ERROR: Version conflict -- dependency tree requires versions conflicting with current setup of product foo: version v2 vs v1"
 sfile=`ups setup -z ./db -B bleem v2`
-[ $sfile = /dev/null ] || echo "Ouch! setup -B bleem v1 should failed"
+[ $sfile = /dev/null ] || echo "Ouch! setup -B bleem v2 should have failed"
+
+: $SETUP_FOO
 
 . `ups unsetup -z ./db foo`
 . `ups setup -z ./db foo v2`
 
 sfile=`ups setup -z ./db -B bleem v2`
 : should have BAR and BAZ but not FOO
-[ $sfile = /dev/null ] &&  echo "Ouch! setup -B bleem v2 should worked"
+[ $sfile = /dev/null ] &&  echo "Ouch! setup -B bleem v2 should have worked"
 if [ `grep SETUP_ $sfile | wc -l` != 3 ]
 then 
     echo FAILED -- wrong dependency count
@@ -47,7 +54,7 @@ fi
 
 . $sfile
 
-sfile=`ups setup ./db -B -z bleem v2`
+sfile=`ups setup -z ./db -B bleem v2`
 : should have nothing -- bleem is already setup
 if [ $sfile != /dev/null ]
 then
