Fix broken test

diff --git a/test/scripts/upstst_exist b/test/scripts/upstst_exist
--- a/test/scripts/upstst_exist
+++ b/test/scripts/upstst_exist
@@ -4,6 +4,6 @@
 # ============================================================================
 cd $UPS_DIR/test/scripts/exist
 $UPS_DIR/bin/ups exist exists v1_0 -f NULL -z ./db1
-if [ ! $? ]; then echo "Exist -- failed to report existing product"; fi
+if [ $? -ne 0 ]; then echo "Exist -- failed to report existing product"; fi
 $UPS_DIR/bin/ups exist doesntexist v1_0 -f NULL -z ./db1
-if [ $? ]; then echo "Exist -- Incorrectly reported nonexistent product"; fi
+if [ $? -eq 0 ]; then echo "Exist -- Incorrectly reported nonexistent product"; fi
